"""How likely a game that has NOT arrived yet is to arrive in the coming year.

WHY THIS EXISTS
---------------
The model answers "when", given that a game arrives. It has no way to say that a
game might simply never come, because every row it was trained on did arrive.
For an old title the result is an estimate that has already passed, which the
site used to render as "could be any time now" - true of almost nothing.

This measures the missing piece directly from the data. For each service, and
for each game age in whole years, it asks: of the games that had not arrived on
this service by that age, how many arrived during the following year?

  chance_next_year(age) = arrived during [age, age+1) / still waiting at age

Candidates are games on any OTHER service's list but not yet on this one - the
same universe the survival experiment used. Nobody is guessing a threshold for
when likelihood decays; the decay is whatever the data shows, per service:

  Game Pass  about 15% for a new release, falling to 2-3% after five years
  PS Plus    about 9%, falling to 4-5% - it keeps picking up older games
  Humble     about 7-9% early, then under 1% once a game is four years old
  Epic       1-2% at every age - it gives away far fewer games than it could

THE HONEST CAVEAT
-----------------
This is a service-wide base rate by age, not a game-specific forecast. It also
counts some candidates that could never have arrived (a console exclusive is not
waiting for Epic), which pulls the figures slightly low. Read it as "games of
this age, on this service" rather than "this game".

Regenerated by deploy on every run, so it tracks the data rather than drifting.
"""

import json
import os
import re

import pandas as pd

from . import config

YEAR = 365.25
MAX_AGE = 15  # anything older reuses the last bucket; the tail is thin


def _norm(name) -> str:
    return re.sub(r"[^a-z0-9]", "", str(name).lower())


def _load(csv_name: str) -> pd.DataFrame:
    df = pd.read_csv(os.path.join(config.DATA_CANONICAL, csv_name))
    df = df[df["game_name"].notna()].copy()
    df["key"] = df["game_name"].map(_norm)
    df["rel"] = pd.to_datetime(df["release_date"], errors="coerce", format="mixed")
    df["added"] = pd.to_datetime(df["Added to Service"], errors="coerce", format="mixed")
    return df


def compute(as_of=None) -> dict:
    """Arrival chance by game age, per canonical dataset (keyed by csv name)."""
    as_of = pd.Timestamp(as_of) if as_of is not None else pd.Timestamp.now().normalize()
    frames = {csv: _load(csv) for csv in config.CANONICAL.values()}

    out = {}
    for csv, mine in frames.items():
        first = (mine.dropna(subset=["rel", "added"])
                     .loc[lambda d: d["added"] <= as_of]
                     .sort_values("added")
                     .drop_duplicates("key"))
        arrived_age = {
            k: (a - r).days / YEAR
            for k, a, r in zip(first["key"], first["added"], first["rel"])
            if (a - r).days >= 0
        }

        others = pd.concat([f for c, f in frames.items() if c != csv], ignore_index=True)
        others = others.dropna(subset=["rel"]).drop_duplicates("key")
        waiting_age = [
            (as_of - r).days / YEAR
            for k, r in zip(others["key"], others["rel"])
            if k not in arrived_age and (as_of - r).days > 0
        ]

        ages_arrived = list(arrived_age.values())
        buckets = []
        for age in range(MAX_AGE + 1):
            at_risk = (sum(1 for a in ages_arrived if a >= age)
                       + sum(1 for a in waiting_age if a >= age))
            arrived = sum(1 for a in ages_arrived if age <= a < age + 1)
            buckets.append({
                "age_years": age,
                "at_risk": at_risk,
                "arrived_next_year": arrived,
                "chance_next_year": round(arrived / at_risk, 4) if at_risk else 0.0,
            })
        out[csv] = buckets
    return {"as_of": as_of.strftime("%Y-%m-%d"), "by_dataset": out}


def run(out_path=None) -> dict:
    table = compute()
    out_path = out_path or os.path.join(config.BACKEND_DIR, "arrival_hazard.json")
    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(table, f, indent=1)
    print(f"Wrote arrival-chance table to {out_path}")
    for csv, buckets in table["by_dataset"].items():
        pts = ", ".join(f"{b['age_years']}y {b['chance_next_year'] * 100:.1f}%"
                        for b in buckets if b["age_years"] in (0, 2, 5, 8))
        print(f"  {csv:9s} {pts}")
    return table


if __name__ == "__main__":
    run()
